name: Bootstrap Inrfastructure
run-name: Bootstrap Infrastructure
on:
  workflow_dispatch:
    inputs:
      project_details:
        description: 'Project Details in JSON format'
        required: true
        type: string
jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub
      run: echo "${{ secrets.TOKEN }}" | gh auth login -h github.com -p https --with-token
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Create values.json
      run: |
        echo '${{ inputs.project_details }}' > values.json

    - name: cat values.json
      run: cat values.json

    - name: Run generate_infra.py
      run: python3 .github/scripts/generate_infra.py 

    - name: Upload infrastructure directory
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure
        path: infrastructure/
        retention-days: 1