name:  Hosted Zones Generation
run-name:  Hosted Zones 
on:
  workflow_dispatch:
    inputs:
      project_details:
        description: 'Project Details in JSON format'
        required: true
        type: string
jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub
      run: echo "${{ secrets.TOKEN }}" | gh auth login -h github.com -p https --with-token

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Create values.json
      run: |
        echo '${{ inputs.project_details }}' > values.json

    - name: cat values.json
      run: ls

    - name: Run generate_infra.py
      run: python3 .github/scripts/generate_infra.py values.json .

    - name: Extract project_name from values.json
      id: extract_project_name
      run: echo "project_name=$(jq -r .project_name values.json)" >> $GITHUB_OUTPUT

    - name: Extract AWS account ID
      id: extract_aws_account_id
      run: |
        aws_account_id=$(jq -r '.environment.Higher["aws-account-id"] // .environment.Lower["aws-account-id"]' values.json)
        echo "aws_account_id=$aws_account_id" >> $GITHUB_OUTPUT

    - name: Create Repository from template
      run: |
        gh repo create ${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra --public --template ${{ github.repository }}

    - name: Sleep for 10 seconds
      run: sleep 10
      
    - name: Create repository variable
      run: |
        gh variable set Default_AWS_ACCOUNT_ID --body "${{ steps.extract_aws_account_id.outputs.aws_account_id }}" --repo FathAllaTechOps/${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra

    - name: Check and set LOWER_AWS_ACCOUNT_ID
      if: ${{ fromJson(inputs.project_details).environment.Lower }}
      run: |
        lower_aws_account_id=$(jq -r '.environment.Lower["aws-account-id"]' values.json)
        gh variable set LOWER_AWS_ACCOUNT_ID --body "$lower_aws_account_id" --repo FathAllaTechOps/${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra

    - name: Check and set HIGHER_AWS_ACCOUNT_ID
      if: ${{ fromJson(inputs.project_details).environment.Higher }}
      run: |
        higher_aws_account_id=$(jq -r '.environment.Higher["aws-account-id"]' values.json)
        gh variable set HIGHER_AWS_ACCOUNT_ID --body "$higher_aws_account_id" --repo FathAllaTechOps/${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra

    - name: Create repository secret
      run: |
        gh secret set TOKEN --body "${{ secrets.TOKEN }}" --repo FathAllaTechOps/${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: FathAllaTechOps/${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra
        token: ${{ secrets.TOKEN }}
        path: ${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra

    - name: Copy infrastructure directory in the development branch
      run: |
        echo "##########" 
        cd ${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra
        git checkout -b development
        cp -r ../infrastructure/* .
        echo "##########"
        python3 ../.github/scripts/check_environment.py .github/workflows/main.yaml ../values.json 


    - name: Commit and push changes
      run: |
        cd ${{ steps.extract_project_name.outputs.project_name }}-hosted-zone-infra
        git config --global user.email "$GITHUB_ACTOR@github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git add .
        git commit -m "Add infrastructure files"
        git push origin development
